version: '2'

services:
  kafka:
    image: spotify/kafka
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      ADVERTISED_PORT: 9092
      ADVERTISED_HOST: '[YOUR MACHINE IP]'



